### ISSUE TITLE
Can't install and use on 2sxc 9.23 or 9.30 on DNN 9.02.00

### ISSUE THREAD

**Issue by jeremy-farrance** [2sic/app-mobius-forms#13]
Tried on a client site as well as a clean install. Install works partially, but fails. Then for the App card you just see "Error". If you go in to App management you can see the logo and app meta data, but there are no data or views or anything. Then, once you delete it and clean up, it takes quite a bit of work deleting folders and files to get 2sxc usable again without errors.

**Comment by iJungleboy** [comment]
I believe this was a bug in 9.23 and affects only apps which were installed in 9.23. Could you verify this?

**Comment by Accuraty** [comment]
My site (DNN 9.02) is already upgraded to 2sxc 9.30 and installing the app fails. What are you asking me to verify?

**Comment by iJungleboy** [comment]
ok, so it's not a 9.23 issue. 

I tried installing on dnn 742 and 2sxc 9.30 and it worked without issues. 

same for dnn 9.2 and 2sxc 9.30

is there any more details you could provide? maybe try installing again and see what the DNN event log says?

**Comment by Accuraty** [comment]
Ok, still on DNN 9.02.00 and 2sxc 9.30. Installed the new Mobius Forms 2. Added the APP module to the Contact page, selected the Mobius Forms 2 app. After a few seconds, the form displayed and everything looked good. I poked around in the app settings (btw, still said 1.03.00 in there), pulled up the docs to see how/where to change the destinations for the emails, cancelled the open dialogs without saving anything, reloaded the page and now instead of the form, this is output (note that the same error is now ALSO being output on the page I had the RSS Feed app on) and none of the 2sxc context/dropdown menus work. I can no longer get in to Edit Templates, Apps Management, etc. and am effectively shut out of 2sxc now (see screen clip below):

`Error: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary. at System.Collections.Generic.Dictionary`2.get_Item(TKey key) at ToSic.Eav.Apps.Template.get_Query() at ToSic.SexyContent.Edit.ClientContextInfo.ClientInfoContentGroup..ctor(SxcInstance sxc, Boolean isCreated) in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\ToSic.Sxc\Edit\ClientContextInfo\ClientInfoContentGroup.cs:line 31 at ToSic.SexyContent.Environment.Dnn7.ClientInfosAll..ctor(String systemRootUrl, PortalSettings ps, IInstanceInfo mic, SxcInstance sxc, UserInfo uinfo, Int32 zoneId, Boolean isCreated, Boolean autoToolbar, Log parentLog) in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\2sxc Dnn\Environment\Dnn7\ClientInfos\ClientInfosAll.cs:line 34 at ToSic.SexyContent.Environment.Dnn7.DnnRenderingHelpers.UiContextInfos(Boolean autoToolbars) in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\2sxc Dnn\Environment\Dnn7\DnnRenderingHelpers.cs:line 123 at ToSic.SexyContent.Environment.Dnn7.DnnRenderingHelpers.ContextAttributes(Int32 instanceId, Int32 contentBlockId, Boolean includeEditInfos, Boolean autoToolbar) in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\2sxc Dnn\Environment\Dnn7\DnnRenderingHelpers.cs:line 78 at ToSic.SexyContent.Environment.Dnn7.DnnRenderingHelpers.WrapInContext(String content, String dontRelyOnParameterOrder, Int32 instanceId, Int32 contentBlockId, Boolean editContext, String tag, Boolean autoToolbar, Boolean addLineBreaks) in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\2sxc Dnn\Environment\Dnn7\DnnRenderingHelpers.cs:line 58 at ToSic.SexyContent.SxcInstance.Render() in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\ToSic.Sxc\SexyContent\SxcInstance_Render.cs:line 76`

![image](https://user-images.githubusercontent.com/653301/39826171-6ece2f0a-5379-11e8-8816-5209f8ef999c.png)

**Comment by iJungleboy** [comment]
I'm guessing this is related to https://github.com/2sic/2sxc/issues/1564 and https://github.com/2sic/2sxc/issues/1561

We're looking into it with high priority.

**Comment by iJungleboy** [comment]
fyi: i'm starting to find the issue, thanks to a new feature I'm building which gives insight to the internal caches. I believe it's related to the global types - i'll keep you posted...

**Comment by iJungleboy** [comment]
I believe this is so old it's not relevant any more.
