### ISSUE TITLE
Feature Request? Single form submission per user

### ISSUE THREAD

**Issue by kingjordan** [2sic/app-mobius-forms#6]
Hello,

Just wondering if it is possible to have a form submitted only once pre logged in user.  I don't think this is built in and was wondering if this is even possible.  

Thanks

**Comment by iJungleboy** [comment]
It could be done, but it's not built in. I'm not sure why you would do this on a technical level. The "fear" that a user could submit multiple times isn't common for form scenarios. What scenario were you thinking of?

**Comment by kingjordan** [comment]
This stems from a client who want to set up a "poll" of thier registered users where they would only be able to submit one questionaire.  If the results log the user id I can filter the results myself, I was just wondering if this was easy to accomplish.

**Comment by iJungleboy** [comment]
Fairly easy, the question is if you would want to "block" the user or just filter it later on. I would recommend placing a user-information in a hidden field, and saving that as well, then filtering it. 

Otherwise you could modify the api (best copy and modify the copy) to review existing items for this user, whichever you prefer. So it's a few hours of work though. 

Note that I'll close the issue, as this won't be something we'll implement soon.

**Comment by kingjordan** [comment]
thanks, close the issue for sure, just was not sure of the best place to ask this question.  I appreciate the follow up
